#!/bin/bash

M2G_VERSION=$1
THIRD_PARTY_DIR=$2
CMAKE_ARGUMENTS="-DCMAKE_INSTALL_PREFIX=$THIRD_PARTY_DIR -DCMAKE_INCLUDE_PATH=$THIRD_PARTY_DIR/include -DCMAKE_LIBRARY_PATH=$THIRD_PARTY_DIR/lib -DSFML_DIR=$THIRD_PARTY_DIR -DBUILD_SHARED_LIBS=1 -DCMAKE_CXX_FLAGS=\"-I$THIRD_PARTY_DIR/include\" "

wget https://github.com/moisesjbc/m2g/archive/v$M2G_VERSION.zip
unzip v$M2G_VERSION.zip
cd m2g-$M2G_VERSION/build
cmake $CMAKE_ARGUMENTS
make install
