#!/bin/bash

TGUI_VERSION=$1
THIRD_PARTY_DIR=$2

CMAKE_ARGUMENTS="-DCMAKE_INSTALL_PREFIX=$THIRD_PARTY_DIR -DCMAKE_INCLUDE_PATH=$THIRD_PARTY_DIR/include -DCMAKE_LIBRARY_PATH=$THIRD_PARTY_DIR/lib -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 -DCMAKE_MODULE_PATH=$THIRD_PARTY_DIR/share/SFML/cmake/Modules/ -DSFML_DIR=$THIRD_PARTY_DIR -DCMAKE_CXX_STANDARD=14 -DTGUI_SHARED_LIBS=1 -DCMAKE_CXX_STANDARD_REQUIRED=1 -DCMAKE_CXX_EXTENSIONS=0"

wget https://github.com/texus/TGUI/archive/v$TGUI_VERSION.zip
unzip v$TGUI_VERSION.zip
cd TGUI-$TGUI_VERSION
cmake $CMAKE_ARGUMENTS
make install
cd $TEMP_DIR
